# Generated by Django 2.1.8 on 2019-06-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
