# Generated by Django 2.1.8 on 2019-06-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('calorieLeft', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('meal', models.CharField(choices=[('breakfast', 'breafast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snacks', 'snack')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('calorie', models.IntegerField()),
                ('unitName', models.CharField(choices=[('g', 'gram'), ('b', 'bowl')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('recordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Daily')),
            ],
        ),
        migrations.CreateModel(
            name='SportsRecord',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('jogging', 'jogging'), ('football', 'football')], max_length=100)),
                ('unitName', models.CharField(choices=[('m', 'meter'), ('min', 'minutes')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('recordID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Daily')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='record',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='record',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='record',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='record',
            name='snacks',
        ),
        migrations.RemoveField(
            model_name='record',
            name='username',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
