# Generated by Django 2.1.8 on 2019-06-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190610_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('dinner', 'dinner'), ('snacks', 'snacks'), ('sports', 'sports')], max_length=10),
        ),
    ]
