# Generated by Django 2.1.8 on 2019-06-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190611_0307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
