# Generated by Django 2.1.8 on 2019-06-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190611_0316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
