# Generated by Django 2.1.8 on 2019-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190611_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsrecord',
            name='calorie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
